### PR TITLE
libdns/netlify: Bump libdns version to v0.2.2

### PR DESCRIPTION
**Pull request by Monviech**
libdns/netlify: Bump libdns version to v0.2.2

I am building this plugin together with cloudflare. Since cloudflare does an indirect upgrade of the libdns version, the build fails.

This PR fixes the build as single module, or together with cloudflare.

### CODE REVIEW

**Review by CL0Pinette — APPROVED** [review]

**Comment by CL0Pinette** [comment]
I will merge it and make a new release

**Comment by CL0Pinette** [comment]
It is now merged in the v1.1.0 version, I am waiting for pkg.go.dev to update the latest version.

**Comment by Monviech** [comment]
Thank you :)

**Comment by CL0Pinette** [comment]
You're welcome, it is now up to date on pkg.go.dev

**Comment by Monviech** [comment]
Thank you, I have tried the build with your new version and it works just fine for me.

**Pull request merged**
